apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  annotations:
  labels:
    strimzi.io/cluster: kafka-kraft
  name: kafka-kraft-rebalance
  namespace: kafka
spec:
  goals:
    - CpuCapacityGoal
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - MinTopicLeadersPerBrokerGoal
    - NetworkOutboundCapacityGoal
    - ReplicaCapacityGoal